id: playbook-urlhaus-feed-Test
version: 3
vcShouldKeepItemLegacyProdMachine: false
name: playbook-urlhaus-feed-Test
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 972ecce2-90f7-4ea8-8e9f-57e69ca73902
    type: start
    task:
      id: 972ecce2-90f7-4ea8-8e9f-57e69ca73902
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "1":
    id: "1"
    taskid: a97228b7-490c-48e9-8887-3bbc45c02245
    type: regular
    task:
      id: a97228b7-490c-48e9-8887-3bbc45c02245
      version: -1
      name: DeleteContext
      description: |-
        Delete field from context.

        This automation runs using the default Limited User role, unless you explicitly change the permissions.
        For more information, see the section about permissions here:
        https://docs.paloaltonetworks.com/cortex/cortex-xsoar/6-2/cortex-xsoar-admin/playbooks/automations.html
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      all:
        simple: "yes"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 230
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "2":
    id: "2"
    taskid: 17dc22ca-3b47-459e-8ad6-b6dac194c382
    type: regular
    task:
      id: 17dc22ca-3b47-459e-8ad6-b6dac194c382
      version: -1
      name: urlhaus-get-indicators
      description: Retrieves a limited number of indicators.
      script: URLhaus Feed|||urlhaus-get-indicators
      type: regular
      iscommand: true
      brand: URLhaus Feed
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 410
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 455,
        "width": 380,
        "x": 450,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
fromversion: 5.5.0