id: playbook-urlhaus-feed_Test
version: 3
vcShouldKeepItemLegacyProdMachine: false
name: playbook-urlhaus-feed_Test
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: f5395793-9614-4840-81e4-c9fb7706ee12
    type: start
    task:
      id: f5395793-9614-4840-81e4-c9fb7706ee12
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "1":
    id: "1"
    taskid: 1dd5002c-a6e0-4243-8f76-45e6d0e9d96a
    type: regular
    task:
      id: 1dd5002c-a6e0-4243-8f76-45e6d0e9d96a
      version: -1
      name: DeleteContext
      description: |-
        Delete field from context.

        This automation runs using the default Limited User role, unless you explicitly change the permissions.
        For more information, see the section about permissions here:
        https://docs.paloaltonetworks.com/cortex/cortex-xsoar/6-2/cortex-xsoar-admin/playbooks/automations.html
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "2"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 230
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "2":
    id: "2"
    taskid: 2af62764-753d-4c00-8ead-8d07429569a6
    type: regular
    task:
      id: 2af62764-753d-4c00-8ead-8d07429569a6
      version: -1
      name: urlhaus-get-indicators
      description: Retrieves a limited number of indicators.
      script: URLhaus Feed|||urlhaus-get-indicators
      type: regular
      iscommand: true
      brand: URLhaus Feed
    nexttasks:
      '#none#':
      - "3"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 410
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "3":
    id: "3"
    taskid: be06794f-a95c-47fc-8d81-3701a96a89d2
    type: regular
    task:
      id: be06794f-a95c-47fc-8d81-3701a96a89d2
      version: -1
      name: closeInvestigation
      description: Close the current incident
      script: Builtin|||closeInvestigation
      type: regular
      iscommand: true
      brand: Builtin
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 580
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 625,
        "width": 380,
        "x": 450,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
fromversion: 5.5.0